version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install ionic and cordova
                command: npm install -g ionic cordova
            - run:
                name: Install npm packages
                command: npm install
            - run:
                name: Install Cordova plugins and add android platform
                command:
                  ionic cordova platform add android --noresources
                  ionic config set -g telemetry true
            - run:
                name: Generate apk
                command:
                  ionic cordova build android --verbose
                  mkdir -p /tmp/apk
                  cp -r platforms/android/app/build/outputs/apk/debug/app-debug.apk /tmp/apk
            - store_artifacts:
                path: /tmp/apk
                destination: apks
workflows:
    build-and-test:
      jobs:
        - build-and-test